### ISSUE TITLE
The color things...

### ISSUE THREAD

**Issue by birkhofflee** [rauchg/wifi-password#21]
<img width="279" alt="screen shot 2017-11-09 at 8 01 56 pm" src="https://user-images.githubusercontent.com/8148095/32604528-e4cb6de6-c588-11e7-9238-96d985b1aa01.png">
<img width="364" alt="screen shot 2017-11-09 at 8 02 03 pm" src="https://user-images.githubusercontent.com/8148095/32604530-e553576a-c588-11e7-8e0d-0c1f8bb13b44.png">

Wish you can solve this. Thanks for making this great tool!

**Comment by RolfKoenders** [comment]
Its probably your color scheme? Using the default iTerm scheme and the ones iTerm ships with it looks good. Don't know if this should be fixed in the module. I would suggest you to check your current scheme.

**Comment by birkhofflee** [comment]
Yes its the color thing. Sorry!
