### ISSUE TITLE
Could have a version for linux too right?

### ISSUE THREAD

**Issue by andersoonweb** [rauchg/wifi-password#3]

**Comment by rauchg** [comment]
Yep. I suggest you do what @RReverser did for Windows, but for your favorite distro(s). Will be happy to link to your project from my README.

**Comment by kevva** [comment]
@rauchg, I created a similar project using node https://github.com/kevva/wifi-password which should work on all OS.

**Comment by rauchg** [comment]
@kevva awesome. As far as Linux goes, is there a single solution that applies to all distributions?

**Comment by andersoonweb** [comment]
Amazing, congratulations @kevva .

**Comment by kevva** [comment]
@rauchg, hm, yeah, currently it's GNOME only. There is probably some way to cover more distros though.
