### ISSUE TITLE
Homebrew compatibility

### ISSUE THREAD

**Issue by jeduan** [rauchg/wifi-password#4]
I went ahead and created a [Homebrew formula](https://gist.github.com/jeduan/f322498b16408c0c946c) however I'm pretty certain that it would be rejected if I submit it as-is.

Looking at the [Acceptable Formulae](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md) I think this is only missing the stable versioning.

**Comment by dmyers** [comment]
:+1:

**Comment by rauchg** [comment]
There's a 0.0.1 tag.

**Comment by rauchg** [comment]
Tagged `0.1.0` with the latest changes
